import { describe, it, expect } from "vitest";
import { getKeywordsFor } from "../data/keywords/index.js";

// These assert the errata delta layer is applied on top of the resolved
// bsdata/faction-pack/manual layers. They are tied to the committed
// errata-keywords.auto.json (regenerated by the errata pass).
describe("getKeywordsFor — errata delta layer", () => {
  it("removes a keyword deleted by errata (Aeldari Warlock Conclave loses CHARACTER)", () => {
    const kw = getKeywordsFor("AELDARI", "Warlock Conclave");
    expect(kw.length).toBeGreaterThan(0); // base keywords still present
    expect(kw).not.toContain("CHARACTER");
  });

  it("removes AIRCRAFT and adds FRAME for a flyer errata'd in the pack", () => {
    const kw = getKeywordsFor("IMPERIAL AGENTS", "Corvus Blackstar");
    expect(kw).not.toContain("AIRCRAFT");
    expect(kw).toContain("FRAME");
  });

  it("leaves a datasheet with no errata untouched", () => {
    const kw = getKeywordsFor("NECRONS", "Necron Warriors");
    expect(kw).toContain("BATTLELINE");
  });

  it("is case/whitespace tolerant on the datasheet name lookup", () => {
    expect(getKeywordsFor("aeldari", "warlock conclave")).not.toContain(
      "CHARACTER"
    );
  });
});

describe("getKeywordsFor — datasheet self-name keyword", () => {
  it("includes the datasheet's own (uppercased) name as a keyword", () => {
    const kw = getKeywordsFor("NECRONS", "Necron Warriors");
    expect(kw).toContain("NECRON WARRIORS");
  });

  it("does not duplicate the name when a layer already supplied it", () => {
    const kw = getKeywordsFor("NECRONS", "Necron Warriors");
    expect(kw.filter((k) => k === "NECRON WARRIORS")).toHaveLength(1);
  });

  it("canonicalises apostrophes in the injected name", () => {
    // Stored/compared in canonical U+2019 form regardless of source punctuation.
    const kw = getKeywordsFor("AELDARI", "Prince Yriel");
    expect(kw).toContain("PRINCE YRIEL");
  });

  it("returns [] (no keyword info) for an entirely uncovered datasheet", () => {
    expect(getKeywordsFor("NECRONS", "Not A Real Datasheet")).toEqual([]);
  });
});
